<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>MiMFa.DaRQ</RootNamespace>
    <Nullable>enable</Nullable>
    <!-- Use SDK default inclusion of source files to avoid duplicate Compile entries -->
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <Company>MiMFa</Company>
    <Product>DaRQ</Product>
    <Authors>Mohammad Fathi (MiMFa)</Authors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="10.0.11" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
  </ItemGroup>


  <ItemGroup>
    <None Include="Library\DaRQ\Global.js" />
    <None Include="LICENSE" />
    <None Include="README.md" />
    <None Include="SAMPLE.md" />
    <None Include="Samples\DaRQ Tutorial-Example.darq" />
    <None Include="Samples\DaRQ Tutorial-Example.js" />
  </ItemGroup>

</Project>
