<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>MiMFa</RootNamespace>
    <!-- Use SDK default inclusion of source files to avoid duplicate Compile entries -->
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <Company>MiMFa</Company>
    <Product>DaRQ</Product>
    <Authors>Mohammad Fathi (MiMFa)</Authors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>


  <ItemGroup>
    <None Include="LICENSE" />
    <None Include="README.md" />
    <None Include="SAMPLE.md" />
    <None Include="Samples\DaRQ Tutorial-Example.darq" />
    <None Include="Samples\DaRQ Tutorial-Example.js" />
  </ItemGroup>


  <ItemGroup>
    <None Update="DaRQ\Library\darq\selector\on.darq">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="DaRQ\Library\darq\selector\one.darq">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="DaRQ\Library\darq\workspace\operators.darq">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="DaRQ\Library\darq\workspace\noises.darq">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="DaRQ\Library\darq\workspace\functions.darq">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="DaRQ\Library\darq\workspace\variables.darq">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="DaRQ\Library\darq\selector\all.darq">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="DaRQ\Library\darq\web\transfer.darq">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="DaRQ\Library\darq\data\resource.darq">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="DaRQ\Library\darq\convert\types.darq">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
